<script setup lang="ts">
definePageMeta({ middleware: 'auth' }); useSeoMeta({ title: '个人中心' })
const auth = useAuth(); const api = useApi(); const settings = useSettingsApi(); const toast = useToast(); const colorMode = useColorMode()
const loading = ref(true); const saving = ref(false); const data = ref<any>(); const form = reactive<Record<string, any>>({})
const goalItems = [{label:'稳妥匹配',value:'fit'},{label:'冲刺发展',value:'stretch'}]
const themeItems = [{label:'跟随系统',value:'system'},{label:'浅色',value:'light'},{label:'深色',value:'dark'}]
const hueItems = [{label:'青',value:'192'},{label:'蓝',value:'220'},{label:'紫',value:'270'},{label:'绿',value:'150'}]
async function load(){loading.value=true;try{const [me,prefs]=await Promise.all([api.ok<{user:any}>('/api/auth/me'),settings.preferences()]);auth.user.value=me.user;data.value=prefs;Object.assign(form,prefs.preferences);if(!prefs.stored){const theme=localStorage.getItem('theme');const hue=localStorage.getItem('hue');const patch:any={};if(theme==='light'||theme==='dark')patch.theme=theme;if(['150','192','220','270'].includes(hue||''))patch.hue=hue;if(Object.keys(patch).length){data.value=await settings.savePreferences(patch);Object.assign(form,data.value.preferences)}}}catch(error){toast.add({title:String(error),color:'error'})}finally{loading.value=false}}
async function save(){saving.value=true;try{data.value=await settings.savePreferences({...form});Object.assign(form,data.value.preferences);colorMode.preference=form.theme;localStorage.setItem('theme',form.theme);localStorage.setItem('hue',form.hue);document.documentElement.style.setProperty('--pathfy-hue',form.hue);toast.add({title:'偏好已保存',color:'success'})}catch(error){toast.add({title:String(error),color:'error'})}finally{saving.value=false}}
onMounted(load)
</script>
<template><div class="page-stack"><div class="page-heading"><h1 class="flex items-center gap-2"><UIcon name="i-lucide-circle-user-round" class="text-primary"/>个人中心</h1><p class="muted">账户、界面、AI 与隐私偏好</p></div><USkeleton v-if="loading" class="h-96"/><template v-else><UCard><template #header><h2 class="font-semibold">账户信息</h2></template><div class="grid gap-3 sm:grid-cols-3"><div><span class="muted">用户名：</span>{{auth.user.value?.username}}</div><div><span class="muted">邮箱：</span>{{auth.user.value?.email}}</div><UBadge :label="auth.isAdmin.value?'管理员':'普通用户'" class="w-fit"/></div></UCard>
<div class="grid gap-4 xl:grid-cols-2"><UCard><template #header><h2 class="font-semibold">外观</h2></template><div class="grid gap-4 sm:grid-cols-2"><UFormField label="主题"><USelect v-model="form.theme" :items="themeItems" class="w-full"/></UFormField><UFormField label="主题色"><USelect v-model="form.hue" :items="hueItems" class="w-full"/></UFormField></div></UCard><UCard><template #header><h2 class="font-semibold">匹配偏好</h2></template><div class="grid gap-4 sm:grid-cols-2"><UFormField label="默认目标"><USelect v-model="form.default_match_goal" :items="goalItems" class="w-full"/></UFormField><UFormField label="结果数量"><UInput v-model.number="form.match_result_count" type="number" min="1" :max="data.limits.match_result_count"/></UFormField><USwitch v-model="form.default_refine_with_llm" label="默认启用 AI 精排"/></div></UCard></div>
<UCard><template #header><div><h2 class="font-semibold">AI 与隐私</h2><p class="text-sm muted">关闭外部 AI 后，个人材料不会发送给第三方模型；依赖模型的功能会使用本地兜底或明确停用。</p></div></template><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><USwitch v-model="form.allow_external_llm" label="允许外部 AI 处理个人数据"/><USwitch v-model="form.report_copywriter" label="报告 AI 文案"/><USwitch v-model="form.report_public_info" label="公开信息增强"/><USwitch v-model="form.report_auto_replan" label="自动重新规划"/><USwitch v-model="form.report_graph_recommendations" label="图谱资源推荐"/><USwitch v-model="form.report_recommendation_llm" label="推荐 AI 精排"/></div></UCard>
<UCard><template #header><h2 class="font-semibold">推荐数量</h2></template><div class="grid gap-4 sm:grid-cols-2"><UFormField label="每个目标的学习资源"><UInput v-model.number="form.learning_resource_count" type="number" min="1" :max="data.limits.learning_resource_count"/></UFormField><UFormField label="每个目标的竞赛"><UInput v-model.number="form.competition_count" type="number" min="0" :max="data.limits.competition_count"/></UFormField></div></UCard><div class="flex justify-end"><UButton icon="i-lucide-save" :loading="saving" @click="save">保存偏好</UButton></div></template></div></template>
