<script setup lang="ts">
definePageMeta({middleware:'admin'});useSeoMeta({title:'图谱管理'})
const api=useApi();const toast=useToast();const stats=ref<Record<string,number>>({});const runs=ref<any[]>([]);const file=ref<File>();const batchSize=ref(128);const mode=ref('merge');const sourceId=ref('');const dryRun=ref(true);const loading=ref('');const lastResult=ref<any>();const clearOpen=ref(false)
async function refresh(){try{stats.value=await api.ok<any>('/api/graph/stats');try{runs.value=(await api.ok<{items:any[]}>('/api/graph/import-runs?limit=20')).items}catch{runs.value=[]}}catch(e){toast.add({title:String(e),color:'error'})}}
function pick(e:Event){file.value=(e.target as HTMLInputElement).files?.[0]}
async function importJobs(){if(!file.value){toast.add({title:'请选择 Excel 文件',color:'warning'});return};if(mode.value==='snapshot'&&!sourceId.value.trim()){toast.add({title:'snapshot 模式必须填写 source_id',color:'warning'});return};loading.value='import';try{const body=new FormData();body.append('file',file.value);body.append('batch_size',String(batchSize.value));body.append('mode',mode.value);body.append('source_id',sourceId.value);body.append('dry_run',String(dryRun.value));lastResult.value=await api.ok<any>('/api/graph/import-jobs',{method:'POST',body});toast.add({title:dryRun.value?'预览完成':'导入完成',color:'success'});await refresh()}catch(e){toast.add({title:String(e),color:'error'})}finally{loading.value=''}}
async function operation(path:string,label:string,dry=true){loading.value=path;try{lastResult.value=await api.ok<any>(path,{method:'POST',body:{dry_run:dry}});toast.add({title:`${label}完成`,color:'success'});await refresh()}catch(e){toast.add({title:String(e),color:'error'})}finally{loading.value=''}}
async function clearGraph(){loading.value='clear';try{await api.ok('/api/graph/clear',{method:'POST',body:{confirmed:true}});clearOpen.value=false;await refresh()}catch(e){toast.add({title:String(e),color:'error'})}finally{loading.value=''}}
onMounted(refresh)
</script>
<template><div class="page-stack"><div class="page-heading"><h1>图谱管理</h1><p class="muted">增量导入、派生数据生成、运行审计和图谱统计</p></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><UCard v-for="(value,key) in stats" :key="key"><p class="text-sm muted">{{key}}</p><p class="mt-2 text-3xl font-bold">{{value}}</p></UCard></div><UCard><template #header><h2 class="text-lg font-semibold">岗位增量导入</h2></template><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><UFormField label="Excel"><UInput type="file" accept=".xls,.xlsx" @change="pick"/></UFormField><UFormField label="批大小"><UInput v-model.number="batchSize" type="number"/></UFormField><UFormField label="模式"><USelect v-model="mode" :items="[{label:'增量合并',value:'merge'},{label:'来源快照',value:'snapshot'}]"/></UFormField><UFormField label="source_id"><UInput v-model="sourceId" :disabled="mode!=='snapshot'" placeholder="recruitment-main"/></UFormField><div class="flex items-end gap-3"><USwitch v-model="dryRun" label="仅预览"/><UButton :loading="loading==='import'" @click="importJobs">执行</UButton></div></div></UCard><UCard><template #header><h2 class="text-lg font-semibold">图谱派生任务</h2></template><div class="flex flex-wrap gap-2"><UButton v-for="item in [{p:'/api/graph/sync/job-titles',l:'同步岗位名称'},{p:'/api/graph/generate/promotion-paths',l:'生成晋升路径'},{p:'/api/graph/generate/lateral-transfers',l:'生成换岗关系'},{p:'/api/graph/generate/learning-resources',l:'生成学习资源'},{p:'/api/graph/generate/competitions',l:'生成竞赛'}]" :key="item.p" color="neutral" variant="soft" :loading="loading===item.p" @click="operation(item.p,item.l,false)">{{item.l}}</UButton><UButton color="error" variant="soft" @click="() => { clearOpen=true }">清空图谱</UButton></div></UCard><UCard v-if="lastResult"><template #header><h2 class="font-semibold">最近结果</h2></template><pre class="overflow-auto whitespace-pre-wrap text-xs">{{JSON.stringify(lastResult,null,2)}}</pre></UCard><UCard><template #header><h2 class="font-semibold">导入运行记录</h2></template><UTable v-if="runs.length" :data="runs"/><UEmpty v-else title="暂无运行记录"/></UCard><UModal v-model:open="clearOpen" title="确认清空图谱"><template #body><p>此操作会删除全部 Neo4j 节点和关系，无法撤销。</p><div class="mt-5 flex justify-end gap-2"><UButton color="neutral" variant="ghost" @click="() => { clearOpen=false }">取消</UButton><UButton color="error" :loading="loading==='clear'" @click="clearGraph">确认清空</UButton></div></template></UModal></div></template>
