<script setup lang="ts">
import type { CodeEnvelope } from '~/types/api'
definePageMeta({ middleware:'auth' }); useSeoMeta({title:'性格测试'})
const api=useApi();const auth=useAuth();const toast=useToast();const questions=ref<any[]>([]);const answers=ref<Record<number,string>>({});const result=ref<any>();const loading=ref(true);const submitting=ref(false);const cacheKey=computed(()=>`career_personality_v1_${auth.user.value?.id||'guest'}`)
function persist(){if(import.meta.client)localStorage.setItem(cacheKey.value,JSON.stringify({v:1,answers:answers.value,result:result.value,savedAt:Date.now()}))}
async function submit(){if(Object.keys(answers.value).length!==questions.value.length){toast.add({title:'请完成全部题目',color:'warning'});return};submitting.value=true;try{const body=await api.request<CodeEnvelope<any>>('/api/personality/submit',{method:'POST',body:{answers:Object.entries(answers.value).map(([id,user_choice])=>({question_id:Number(id),user_choice}))}});if(body.code!==200)throw new Error(body.msg||'提交失败');result.value=body.data;persist();toast.add({title:'测试完成',color:'success'})}catch(e){toast.add({title:String(e),color:'error'})}finally{submitting.value=false}}
onMounted(async()=>{auth.hydrate();const raw=localStorage.getItem(cacheKey.value);if(raw)try{const c=JSON.parse(raw);answers.value=c.answers||{};result.value=c.result}catch{};try{const body=await api.request<CodeEnvelope<any[]>>('/api/personality/questions');if(body.code===200)questions.value=body.data||[]}finally{loading.value=false}})
watch(answers,persist,{deep:true})
</script>
<template><div class="page-stack"><div class="page-heading"><h1>职业性格测试</h1><p class="muted">通过 MBTI 维度了解职业偏好与成长方向</p></div><USkeleton v-if="loading" class="h-96"/><template v-else-if="!result"><UProgress :model-value="Object.keys(answers).length" :max="questions.length"/><UCard v-for="(q,index) in questions" :key="q.id"><template #header><h2 class="font-medium">{{index+1}}. {{q.question_text}}</h2></template><URadioGroup v-model="answers[q.id]" :items="[{label:q.option_a,value:'A'},{label:q.option_b,value:'B'}]" /></UCard><UButton size="xl" block :loading="submitting" @click="submit">提交测试</UButton></template><template v-else><UCard><div class="text-center"><p class="text-5xl font-bold text-primary">{{result.mbti_type}}</p><h2 class="mt-3 text-xl font-semibold">{{result.complete_analysis?.name||'性格分析'}}</h2><p class="mx-auto mt-4 max-w-3xl muted">{{result.complete_analysis?.summary||result.personality_analysis}}</p></div></UCard><div class="panel-grid two"><UCard><template #header><h2 class="font-semibold">核心优势</h2></template><ul class="list-disc space-y-2 pl-5"><li v-for="x in result.complete_analysis?.core_strengths||[]" :key="x">{{x}}</li></ul></UCard><UCard><template #header><h2 class="font-semibold">推荐岗位</h2></template><div class="flex flex-wrap gap-2"><UBadge v-for="x in result.recommended_jobs||[]" :key="x" :label="x"/></div></UCard></div><UButton variant="outline" @click="result=null;persist()">重新测试</UButton></template></div></template>
