<script setup lang="ts">
import type { CapabilityScores, CodeEnvelope } from '~/types/api'
definePageMeta({ middleware: 'auth' }); useSeoMeta({ title: '能力画像' })
const api=useApi(); const auth=useAuth(); const toast=useToast(); const name=ref(''); const major=ref(''); const text=ref(''); const files=ref<File[]>([]); const loading=ref(false); const result=ref<any>();
const cacheKey=computed(()=>`career_profile_portrait_v1_${auth.user.value?.id || 'guest'}`)
function choose(event:Event){const selected=Array.from((event.target as HTMLInputElement).files||[]);files.value=[...files.value,...selected].slice(0,12)}
function removeFile(i:number){files.value.splice(i,1)}
async function submit(){if(!name.value||!major.value||(!files.value.length&&!text.value.trim())){toast.add({title:'请填写姓名、专业并提供至少一份材料',color:'warning'});return};loading.value=true;try{const body=new FormData();body.append('name',name.value);body.append('major',major.value);if(text.value)body.append('profile_text',text.value);for(const file of files.value)body.append('materials',file);const response=await api.request<CodeEnvelope<any>>('/api/profile/upload',{method:'POST',body});if(response.code!==200)throw new Error(response.msg||'分析失败');result.value=response.data;localStorage.setItem(cacheKey.value,JSON.stringify({v:1,savedAt:Date.now(),...response.data}));toast.add({title:'能力画像生成成功',color:'success'})}catch(e){toast.add({title:e instanceof Error?e.message:'分析失败',color:'error'})}finally{loading.value=false}}
onMounted(()=>{auth.hydrate();const raw=localStorage.getItem(cacheKey.value);if(raw)try{result.value=JSON.parse(raw)}catch{}})
const scores=computed<Partial<CapabilityScores>>(()=>result.value?.scores||{})
</script>
<template><div class="page-stack"><div class="page-heading"><h1>学生就业能力画像</h1><p class="muted">上传简历、证书、成绩单或项目说明，生成八维能力分析</p></div><div class="grid gap-4 lg:grid-cols-[380px_1fr]"><UCard><div class="grid gap-4"><UFormField label="姓名"><UInput v-model="name" class="w-full"/></UFormField><UFormField label="专业"><UInput v-model="major" class="w-full"/></UFormField><UFormField label="上传材料" hint="最多 12 份"><UInput type="file" multiple class="w-full" @change="choose" /></UFormField><div v-if="files.length" class="grid gap-2"><div v-for="(file,i) in files" :key="`${file.name}-${i}`" class="flex items-center justify-between rounded-md bg-muted px-3 py-2 text-sm"><span class="truncate">{{file.name}}</span><UButton icon="i-lucide-x" size="xs" color="neutral" variant="ghost" @click="removeFile(i)"/></div></div><UFormField label="补充文本"><UTextarea v-model="text" :rows="6" class="w-full"/></UFormField><UButton block :loading="loading" @click="submit">生成能力画像</UButton></div></UCard><div class="grid gap-4"><UCard><CapabilityRadar :scores="scores" height="360px"/></UCard><div v-if="result" class="grid gap-4 sm:grid-cols-2"><UCard><p class="muted">能力完整度</p><p class="mt-2 text-3xl font-bold">{{result.completeness||0}}</p><UProgress :model-value="result.completeness||0" class="mt-3"/></UCard><UCard><p class="muted">就业竞争力</p><p class="mt-2 text-3xl font-bold">{{result.competitiveness||0}}</p><UProgress :model-value="result.competitiveness||0" class="mt-3"/></UCard></div></div></div><template v-if="result?.detailed_analysis"><UCard><template #header><h2 class="text-xl font-semibold">整体评价</h2></template><p>{{result.detailed_analysis.overall_evaluation||'暂无'}}</p></UCard><div class="panel-grid two"><UCard v-for="key in ['advantage_dimensions','劣势_dimensions','short_term_plan','long_term_goals','industry_match']" :key="key"><template #header><h2 class="font-semibold">{{({advantage_dimensions:'优势维度','劣势_dimensions':'待提升维度',short_term_plan:'短期计划',long_term_goals:'长期目标',industry_match:'行业适配'} as any)[key]}}</h2></template><pre class="whitespace-pre-wrap text-sm">{{JSON.stringify(result.detailed_analysis[key],null,2)}}</pre></UCard></div></template></div></template>
