<script setup lang="ts">
definePageMeta({ middleware: 'auth' }); useSeoMeta({ title: '岗位探索' })
const api = useJobsApi(); const toast = useToast(); const q = ref(''); const sort = ref('default'); const page = ref(1); const loading = ref(false); const result = ref<any>({ jobs: [], total: 0, total_pages: 1 }); const selected = ref<string|null>(null); const assistantOpen = ref(false); const message = ref(''); const answer = ref(''); const assistantSessions = ref<any[]>([]); const sessionId = ref<number>();
async function load() { loading.value = true; try { result.value = await api.list({ q: q.value, sort: sort.value, page: page.value, seed: sort.value === 'random' ? 'pathfy' : '' }) } catch(e) { toast.add({title:String(e),color:'error'}) } finally { loading.value=false } }
async function ask() { if(!message.value.trim()) return; loading.value=true; try { const r=await api.chat(message.value, sessionId.value); sessionId.value=r.session_id||sessionId.value; answer.value=r.reply || r.message || JSON.stringify(r); assistantSessions.value=(await api.sessions()).sessions||[] } catch(e){toast.add({title:String(e),color:'error'})} finally{loading.value=false} }
async function openAssistant(){assistantOpen.value=true;try{assistantSessions.value=(await api.sessions()).sessions||[]}catch{assistantSessions.value=[]}}
async function restoreSession(id:number){sessionId.value=id;try{const r=await api.session(id);answer.value=(r.messages||[]).map((x:any)=>`${x.role==='user'?'我':'AI'}：${x.content}`).join('\n\n')}catch(e){toast.add({title:String(e),color:'error'})}}
watch([page, sort], load); onMounted(load)
</script>
<template><div class="page-stack"><div class="flex flex-wrap items-end justify-between gap-3"><div class="page-heading"><h1>岗位探索</h1><p class="muted">检索岗位、查看八维需求并咨询 AI 助手</p></div><UButton icon="i-lucide-message-circle" variant="soft" @click="() => { assistantOpen=true }">岗位助手</UButton></div><UCard><form class="flex flex-wrap gap-3" @submit.prevent="page=1;load()"><UInput v-model="q" placeholder="岗位、公司或地点" class="min-w-60 flex-1" /><USelect v-model="sort" :items="[{label:'综合排序',value:'default'},{label:'要求从高到低',value:'score_desc'},{label:'要求从低到高',value:'score_asc'},{label:'随机浏览',value:'random'}]" class="w-48" /><UButton type="submit">搜索</UButton></form></UCard><div v-if="loading" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><USkeleton v-for="n in 6" :key="n" class="h-44" /></div><div v-else-if="result.jobs.length" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><UCard v-for="job in result.jobs" :key="job.id"><h2 class="text-lg font-semibold">{{ job.title }}</h2><p class="mt-1 text-sm muted">{{ job.company }} · {{ job.location }}</p><p class="mt-3 font-medium text-primary">{{ job.salary }}</p><div class="mt-4 flex justify-between"><UBadge :label="`综合 ${job.score_avg || 0}`" variant="soft" /><UButton size="sm" variant="ghost" @click="() => { selected=job.id }">查看详情</UButton></div></UCard></div><UEmpty v-else title="没有匹配岗位" icon="i-lucide-search-x" /><UPagination v-model:page="page" :total="result.total" :items-per-page="result.page_size || 20" /><JobDetailModal :job-id="selected" @close="selected=null" /><USlideover v-model:open="assistantOpen" title="岗位 AI 助手"><template #body><div class="grid gap-4"><UTextarea v-model="message" :rows="5" placeholder="例如：我适合哪些数据岗位？" /><UButton :loading="loading" @click="ask">发送</UButton><UCard v-if="answer"><p class="whitespace-pre-wrap">{{ answer }}</p></UCard></div></template></USlideover></div></template>
