<script setup lang="ts">
import type { ResumeOption } from '~/types/profile'
defineProps<{ items: ResumeOption[]; loading: boolean; restoringId?: number; error?: string }>()
defineEmits<{ restore: [id: number]; retry: [] }>()
const open = defineModel<boolean>('open', { required: true })
function dateText(value?: string) { return value ? value.replace('T', ' ').slice(0, 19) : '时间未知' }
</script>
<template><UModal v-model:open="open" title="历史能力画像" description="服务器中最新画像优先于本地缓存"><template #body><UAlert v-if="error" color="error" variant="soft" icon="i-lucide-circle-alert" title="历史画像加载失败" :description="error"><template #actions><UButton size="sm" color="error" variant="outline" @click="$emit('retry')">重试</UButton></template></UAlert><div v-if="loading" class="mt-3 grid gap-2"><USkeleton v-for="n in 3" :key="n" class="h-20" /></div><div v-else class="mt-3 grid gap-2"><button v-for="item in items" :key="item.id" type="button" class="history-row" :disabled="Boolean(restoringId)" @click="$emit('restore', item.id)"><div><p class="font-medium">{{ item.name || '未命名' }} · {{ item.major || '专业未知' }}</p><p class="mt-1 text-xs muted">画像 #{{ item.id }} · {{ dateText(item.create_time || item.created_at) }}</p></div><div class="text-right"><UIcon v-if="restoringId === item.id" name="i-lucide-loader-circle" class="animate-spin" /><template v-else><p class="font-semibold">{{ Math.round(item.score_avg || 0) }} 分</p><p class="text-xs muted">完整度 {{ Math.round(item.completeness || 0) }}</p></template></div></button><UEmpty v-if="!items.length && !error" title="暂无历史画像" /></div></template></UModal></template>
<style scoped>.history-row { display:flex; align-items:center; justify-content:space-between; gap:.75rem; width:100%; border:1px solid var(--ui-border); border-radius:.75rem; padding:.8rem; text-align:left; } .history-row:hover,.history-row:focus-visible { border-color:var(--ui-primary); outline:none; } .history-row:focus-visible { box-shadow:0 0 0 2px color-mix(in srgb,var(--ui-primary) 28%,transparent); }</style>
