<script setup lang="ts">
import { graphStatusLabels, summaryLabels, taskDangerous, taskLabel } from '~/types/graph'
definePageMeta({middleware:'admin'});useSeoMeta({title:'图谱任务详情'})
const route=useRoute();const graph=useGraphTasksApi();const toast=useToast();const task=ref<any>();const guard=ref<any>();const loading=ref('');const downloading=ref('');const rejectOpen=ref(false);const confirmOpen=ref(false);const reverseOpen=ref(false);const reason=ref('');let timer:ReturnType<typeof setInterval>|undefined
async function load(){try{[task.value,guard.value]=await Promise.all([graph.task(String(route.params.id)),graph.guard()])}catch(error){toast.add({title:String(error),color:'error'})}}
async function download(file:any){downloading.value=file.role;try{const blob=await graph.downloadFile(task.value.id,file.role);const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=file.original_name||`${file.role}.dat`;anchor.click();URL.revokeObjectURL(url)}catch(error){toast.add({title:String(error),color:'error'})}finally{downloading.value=''}}
async function confirm(){loading.value='confirm';try{await graph.confirm(task.value.id);confirmOpen.value=false;toast.add({title:'已确认，等待 worker 提交',color:'success'});await load()}catch(error){toast.add({title:String(error),color:'error'})}finally{loading.value=''}}
async function reject(){loading.value='reject';try{await graph.reject(task.value.id,reason.value);rejectOpen.value=false;await load()}catch(error){toast.add({title:String(error),color:'error'})}finally{loading.value=''}}
async function createReverse(){loading.value='reverse';try{const result=await graph.reverse(task.value.id);reverseOpen.value=false;toast.add({title:'恢复任务已生成，请审阅后确认',color:'success'});await navigateTo(`/graph-admin/tasks/${result.id}`)}catch(error){toast.add({title:String(error),color:'error'})}finally{loading.value=''}}
function detailRows(detail:any){return Object.entries(detail||{}).filter(([,value])=>value===null||['string','number','boolean'].includes(typeof value)).slice(0,6)}
function openReject(){rejectOpen.value=true}function openConfirm(){confirmOpen.value=true}function closeConfirm(){confirmOpen.value=false}function openReverse(){reverseOpen.value=true}function closeReverse(){reverseOpen.value=false}
onMounted(async()=>{await load();timer=setInterval(()=>{if(['queued','running','applying'].includes(task.value?.status))load()},3000)});onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>

<template><div class="page-stack"><GraphAdminNav/><GraphGuardBanner :guard="guard"/><template v-if="task"><div class="flex flex-wrap items-end justify-between gap-3"><div class="page-heading"><div class="flex items-center gap-2"><h1 class="flex items-center gap-2"><UIcon name="i-lucide-clipboard-list" class="text-primary"/>任务 #{{ task.id }}</h1><UBadge v-if="taskDangerous(task.task_type)" label="危险操作" color="error"/></div><p class="muted">{{ taskLabel(task.task_type) }}</p></div><div class="flex gap-2"><UButton v-if="task.status==='succeeded'&&task.inverse_available&&!task.inverse_of_task_id" color="warning" variant="soft" icon="i-lucide-rotate-ccw" @click="openReverse">生成恢复任务</UButton><template v-if="task.status==='awaiting_confirmation'"><UButton color="error" variant="soft" @click="openReject">拒绝</UButton><UButton @click="openConfirm">确认整单变更</UButton></template></div></div>
<UAlert v-if="task.status==='applying'&&!task.neo4j_committed_at" color="info" icon="i-lucide-loader-circle" title="等待提交图谱" description="管理员确认已记录，graph worker 将校验变更集并在 Neo4j 事务中提交。"/>
<UAlert v-else-if="task.status==='applying'&&['pending','running','retrying'].includes(task.projection_status)" :color="task.projection_status==='retrying'?'warning':'info'" icon="i-lucide-refresh-cw" title="图谱已提交，派生索引同步中" :description="task.projection_error||`Neo4j revision 已更新，正在同步 MySQL 岗位名称投影（第 ${task.projection_attempts||0} 次）。`"/>
<div class="grid gap-3 md:grid-cols-5"><UCard><p class="text-sm muted">状态</p><UBadge class="mt-2" :label="graphStatusLabels[task.status]||task.status"/></UCard><UCard><p class="text-sm muted">图谱 revision</p><p class="mt-2 text-xl font-semibold">{{ task.base_graph_revision??'-' }}</p></UCard><UCard><p class="text-sm muted">设置 revision</p><p class="mt-2 text-xl font-semibold">{{ task.settings_revision??'旧环境配置' }}</p></UCard><UCard><p class="text-sm muted">来源与模式</p><p class="mt-2 font-medium">{{ task.source_id||'-' }} · {{ task.mode }}</p></UCard><UCard><p class="text-sm muted">创建时间</p><p class="mt-2 text-sm font-medium">{{ task.created_at }}</p></UCard></div>
<UCard v-if="task.files?.length"><template #header><div><h2 class="font-semibold">输入文件</h2><p class="text-sm muted">原始数据集保存在后端私有目录，仅管理员可下载</p></div></template><div class="grid gap-3"><div v-for="file in task.files" :key="file.id||file.role" class="grid items-center gap-2 rounded-lg border border-default p-3 md:grid-cols-[8rem_1fr_auto_auto]"><strong>{{ file.role }}</strong><span class="min-w-0 truncate" :title="file.original_name">{{ file.original_name }}</span><span class="text-sm muted">{{ file.size }} bytes</span><UButton v-if="file.available" size="xs" variant="soft" icon="i-lucide-download" :loading="downloading===file.role" @click="download(file)">下载</UButton><UBadge v-else label="旧文件已清理" color="neutral" variant="soft"/><code class="break-all text-xs text-muted md:col-span-4">SHA-256 {{ file.sha256 }}</code></div></div></UCard>
<UCard><template #header><h2 class="font-semibold">更新摘要</h2></template><GraphTaskSummary :summary="task.change_summary"/></UCard>
<UCard v-if="task.change_set_sha256"><template #header><div><h2 class="font-semibold">变更明细</h2><p class="text-sm muted">按类型分页审阅，完整变更集由后端哈希保护</p></div></template><GraphTaskChanges :task-id="task.id" :enabled="Boolean(task.change_set_sha256)"/></UCard>
<UAlert v-if="task.error_message" color="error" icon="i-lucide-circle-x" title="任务错误" :description="task.error_message"/>
<UCard><template #header><h2 class="font-semibold">任务时间线</h2></template><div class="grid gap-5"><div v-for="event in task.events" :key="event.id" class="relative border-l-2 border-primary pl-5"><span class="absolute -left-1.5 top-1 size-2.5 rounded-full bg-primary"/><div class="flex flex-wrap justify-between gap-2"><strong>{{ event.message }}</strong><span class="text-xs muted">{{ event.created_at }}</span></div><p class="mt-1 text-sm muted">{{ event.stage }} · {{ event.event_type }}</p><div v-if="detailRows(event.detail).length" class="mt-2 flex flex-wrap gap-2"><UBadge v-for="([key,value]) in detailRows(event.detail)" :key="key" color="neutral" variant="soft" :label="`${summaryLabels[key]||key}: ${value}`"/></div></div></div></UCard>
</template><USkeleton v-else class="h-80"/>
<UModal v-model:open="rejectOpen" title="拒绝整单变更"><template #body><UTextarea v-model="reason" :rows="5" placeholder="填写拒绝原因"/><div class="mt-4 flex justify-end"><UButton color="error" :disabled="!reason.trim()" :loading="loading==='reject'" @click="reject">确认拒绝</UButton></div></template></UModal>
<UModal v-model:open="confirmOpen" :title="taskDangerous(task?.task_type)?'确认危险图谱操作':'确认应用整单变更'"><template #body><UAlert :color="taskDangerous(task?.task_type)?'error':'warning'" icon="i-lucide-triangle-alert" :title="taskDangerous(task?.task_type)?'本任务包含不可恢复的节点删除':'确认后将修改线上 Neo4j'" description="系统会再次校验写锁、revision 和变更集哈希，并在一个事务中应用。"/><div class="mt-4 flex justify-end gap-2"><UButton variant="ghost" @click="closeConfirm">取消</UButton><UButton :color="taskDangerous(task?.task_type)?'error':'primary'" :loading="loading==='confirm'" @click="confirm">确认应用</UButton></div></template></UModal>
<UModal v-model:open="reverseOpen" title="生成恢复任务"><template #body><UAlert color="warning" icon="i-lucide-rotate-ccw" title="恢复也需要再次审阅" description="系统只恢复本任务执行前已经固化的岗位属性；若图谱 revision 已继续变化，将拒绝创建以避免覆盖后续更新。"/><div class="mt-4 flex justify-end gap-2"><UButton variant="ghost" @click="closeReverse">取消</UButton><UButton color="warning" :loading="loading==='reverse'" @click="createReverse">生成并审阅</UButton></div></template></UModal>
</div></template>
