<script setup lang="ts">
import { graphStatusLabels, graphTaskCatalog, taskDangerous, taskLabel } from '~/types/graph'
definePageMeta({ middleware: 'admin' }); useSeoMeta({ title: '图谱任务队列' })
const graph=useGraphTasksApi();const toast=useToast();const data=ref<any>({items:[],total:0});const page=ref(1);const status=ref('all');const type=ref('all');const requestedBy=ref<number>();const createdFrom=ref('');const createdTo=ref('');const guard=ref<any>();const cancelTarget=ref<any>();const cancelling=ref(false)
const statusItems=[{label:'全部状态',value:'all'},...Object.entries(graphStatusLabels).map(([value,label])=>({label,value}))]
const typeItems=[{label:'全部类型',value:'all'},...Object.entries(graphTaskCatalog).map(([value,item])=>({label:`${item.category} · ${item.label}`,value}))]
async function load(){try{[data.value,guard.value]=await Promise.all([graph.tasks({page:page.value,status:status.value==='all'?'':status.value,task_type:type.value==='all'?'':type.value,requested_by:requestedBy.value,created_from:createdFrom.value?`${createdFrom.value} 00:00:00`:'',created_to:createdTo.value?`${createdTo.value} 23:59:59`:''}),graph.guard()])}catch(error){toast.add({title:String(error),color:'error'})}}
async function cancel(){if(!cancelTarget.value)return;cancelling.value=true;try{await graph.cancel(cancelTarget.value.id);cancelTarget.value=undefined;toast.add({title:'排队任务已取消',color:'success'});await load()}catch(error){toast.add({title:String(error),color:'error'})}finally{cancelling.value=false}}
function openCancel(item:any){cancelTarget.value=item}
function descriptor(item:any){if(item.files?.length)return item.files.map((file:any)=>file.original_name).join('、');if(item.options?.scope)return `范围：${item.options.scope}`;if(item.task_type==='salary_normalization')return item.options?.force?'全部岗位':'仅缺失或过期';if(item.task_type==='inferred_job_cleanup')return 'inferred Job 与低频 JobTitle';return '无文件维护任务'}
watch([page,status,type],()=>{page.value=page.value||1;load()});onMounted(load)
</script>

<template><div class="page-stack"><GraphAdminNav/><GraphGuardBanner :guard="guard"/><div class="page-heading"><h1 class="flex items-center gap-2"><UIcon name="i-lucide-history" class="text-primary"/>历史任务队列</h1><p class="muted">所有图谱写入都在这里留下可追溯记录</p></div>
<UCard><div class="flex flex-wrap gap-3"><USelect v-model="status" :items="statusItems" class="w-48"/><USelect v-model="type" :items="typeItems" class="w-64"/><UInput v-model.number="requestedBy" type="number" min="1" placeholder="申请人 ID" class="w-32"/><UInput v-model="createdFrom" type="date"/><UInput v-model="createdTo" type="date"/><UButton variant="soft" @click="page=1;load()">查询</UButton><span class="ml-auto self-center text-sm muted">共 {{ data.total }} 个任务</span></div></UCard>
<div class="grid gap-3"><UCard v-for="item in data.items" :key="item.id"><div class="flex flex-wrap items-center justify-between gap-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-semibold">#{{ item.id }}</span><UBadge :label="graphStatusLabels[item.status]||item.status"/><UBadge :label="taskLabel(item.task_type)" color="neutral" variant="soft"/><UBadge v-if="taskDangerous(item.task_type)" label="危险操作" color="error" variant="soft"/></div><p class="mt-2 truncate font-medium">{{ descriptor(item) }}</p><p class="mt-1 text-sm muted">{{ item.source_id||'无来源标识' }} · {{ item.mode }} · 申请人 #{{ item.requested_by }} · {{ item.files?.length||0 }} 个文件 · {{ item.created_at }}</p></div><div class="flex gap-2"><UButton :to="`/graph-admin/tasks/${item.id}`" variant="soft">查看详情</UButton><UButton v-if="item.status==='queued'" color="error" variant="ghost" @click="openCancel(item)">取消</UButton></div></div></UCard><UEmpty v-if="!data.items.length" title="暂无符合条件的任务"/></div>
<UPagination v-if="data.total>20" v-model:page="page" :total="data.total" :items-per-page="20"/>
<UModal :open="Boolean(cancelTarget)" title="确认取消排队任务" @update:open="value=>{if(!value)cancelTarget=undefined}"><template #body><UAlert color="warning" icon="i-lucide-triangle-alert" title="本操作只取消尚未执行的任务，不会修改 Neo4j"/><dl class="mt-4 grid gap-2 text-sm"><div><dt class="muted">任务</dt><dd>#{{ cancelTarget?.id }} · {{ taskLabel(cancelTarget?.task_type) }}</dd></div><div><dt class="muted">影响范围</dt><dd>{{ cancelTarget ? descriptor(cancelTarget) : '-' }}；{{ cancelTarget?.files?.length||0 }} 个输入文件</dd></div></dl><div class="mt-4 flex justify-end gap-2"><UButton variant="ghost" @click="cancelTarget=undefined">返回</UButton><UButton color="error" :loading="cancelling" @click="cancel">确认取消任务</UButton></div></template></UModal>
</div></template>
