<script setup lang="ts">
definePageMeta({middleware:'admin'});useSeoMeta({title:'更新图谱'})
const graph=useGraphTasksApi();const toast=useToast();const type=ref('job_import');const file=ref<File>();const mode=ref('merge');const sourceId=ref('');const batch=ref(128);const promotions=ref(true);const lateral=ref(true);const loading=ref(false);const guard=ref<any>()
const typeItems=[{label:'岗位 Excel',value:'job_import'},{label:'学习资源 CSV',value:'learning_resource_import'},{label:'竞赛 CSV',value:'competition_import'}]
function pick(e:Event){file.value=(e.target as HTMLInputElement).files?.[0]}
async function submit(){if(!file.value){toast.add({title:'请选择文件',color:'warning'});return}if(mode.value==='snapshot'&&!sourceId.value.trim()){toast.add({title:'snapshot 必须填写 source_id',color:'warning'});return}loading.value=true;try{const body=new FormData();body.append('task_type',type.value);body.append('file',file.value);body.append('mode',mode.value);body.append('source_id',sourceId.value);body.append('batch_size',String(batch.value));body.append('generate_promotions',String(promotions.value));body.append('generate_lateral',String(lateral.value));const task=await graph.create(body);toast.add({title:'任务已进入队列',color:'success'});await navigateTo(`/graph-admin/tasks/${task.id}`)}catch(e){toast.add({title:String(e),color:'error'})}finally{loading.value=false}}
watch(type, value=>{if(value==='job_import'){mode.value='merge';sourceId.value=''}else{mode.value='snapshot';sourceId.value=value==='learning_resource_import'?'master-learning-resources':'master-competitions'}})
onMounted(async()=>{guard.value=await graph.guard()})
</script>
<template><div class="page-stack"><GraphAdminNav/><GraphGuardBanner :guard="guard"/><div class="page-heading"><h1>更新图谱</h1><p class="muted">上传数据后由 worker 生成待确认变更，不会立即修改 Neo4j</p></div><UCard><div class="grid gap-5 md:grid-cols-2"><UFormField label="任务类型"><USelect v-model="type" :items="typeItems" class="w-full"/></UFormField><UFormField label="文件"><UInput type="file" :accept="type==='job_import'?'.xls,.xlsx':'.csv'" @change="pick"/></UFormField><UFormField label="导入模式"><USelect v-model="mode" :items="[{label:'增量合并',value:'merge'},{label:'来源快照',value:'snapshot'}]"/></UFormField><UFormField label="source_id"><UInput v-model="sourceId" placeholder="recruitment-main / master-resources"/></UFormField><UFormField v-if="type==='job_import'" label="批大小"><UInput v-model.number="batch" type="number" min="1" max="1000"/></UFormField><div v-if="type==='job_import'" class="grid gap-2"><UCheckbox v-model="promotions" label="生成晋升路径"/><UCheckbox v-model="lateral" label="生成换岗关系"/><p class="text-sm muted">岗位名称始终自动同步。</p></div></div><UAlert v-if="type==='learning_resource_import'" class="mt-5" title="学习资源 CSV" description="使用 master/learning_resources.csv 字段契约。"/><UAlert v-if="type==='competition_import'" class="mt-5" title="竞赛 CSV" description="使用 master/competitions.csv 字段契约。"/><UButton class="mt-6" size="lg" :loading="loading" @click="submit">创建更新任务</UButton></UCard></div></template>
